paginate: 10
pygments: true
highlighter: pygments
safe: true
permalink: /:year/:month/:title.html
relative_permalinks: false
title: code. hack it.
tagline: /dev/random
excerpt_separator: N/A-------N/A... Workaround for https://github.com/mojombo/jekyll/issues/1401
